openapi: 3.1.0
info:
  title: event-analytics API
  version: 1.0.0
  description: API documentation for the event-analytics backend
servers:
  - url: http://localhost:4000/api

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key

  parameters:
    ApiKeyHeader:
      in: header
      name: x-api-key
      schema:
        type: string
      required: true
      description: API key for authentication

  schemas:
    ApiKey:
      type: object
      properties:
        _id:
          type: string
        key:
          type: string
        orgId:
          type: string
        projectId:
          type: string
        isActive:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        __v:
          type: integer

    Event:
      type: object
      properties:
        _id:
          type: string
        userId:
          type: string
        eventName:
          type: string
        timestamp:
          type: string
          format: date-time
        orgId:
          type: string
        projectId:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        __v:
          type: integer

    MetricsResponse:
      type: object
      properties:
        eventName:
          type: string
        totalEvents:
          type: integer
        uniqueUsers:
          type: integer
        dailyBreakdown:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
              count:
                type: integer

    FunnelResponse:
      type: object
      properties:
        steps:
          type: array
          items:
            type: object
            properties:
              event:
                type: string
              users:
                type: integer

    RetentionResponse:
      type: object
      properties:
        cohort:
          type: string
        retention:
          type: array
          items:
            type: object
            properties:
              day:
                type: integer
              users:
                type: integer

    JourneyResponse:
      type: object
      properties:
        journeys:
          type: array
          items:
            type: object
            properties:
              userId:
                type: string
              events:
                type: array
                items:
                  type: string

    UserJourneyResponse:
      type: object
      properties:
        userId:
          type: string
        events:
          type: array
          items:
            type: object
            properties:
              event:
                type: string
              timestamp:
                type: string
                format: date-time

paths:
  /protected:
    get:
      summary: Test protected endpoint
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: "#/components/parameters/ApiKeyHeader"
      responses:
        "200":
          description: Success

  /apikeys/active:
    get:
      summary: Get all active API keys
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: "#/components/parameters/ApiKeyHeader"
      responses:
        "200":
          description: List of active API keys
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiKey"

  /generate-api-key:
    post:
      summary: Generate a new API key for an organization/project
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: "#/components/parameters/ApiKeyHeader"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                orgName:
                  type: string
                projectName:
                  type: string
      responses:
        "200":
          description: Returns the newly created API key
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiKey"

  /events:
    post:
      summary: Ingest event(s)
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: "#/components/parameters/ApiKeyHeader"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/components/schemas/Event"
                - type: array
                  items:
                    $ref: "#/components/schemas/Event"
      responses:
        "200":
          description: Event(s) ingested

  /events/metrics:
    get:
      summary: Metrics for a single event type
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: "#/components/parameters/ApiKeyHeader"
        - name: eventName
          in: query
          required: true
          schema:
            type: string
        - name: period
          in: query
          required: false
          schema:
            type: string
            example: "7d"
      responses:
        "200":
          description: Event metrics
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MetricsResponse"

  /events/funnel:
    get:
      summary: Get funnel data for a list of event steps
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: "#/components/parameters/ApiKeyHeader"
        - name: events
          in: query
          required: true
          description: Comma-separated event names
          schema:
            type: string
        - name: period
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Funnel analysis
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FunnelResponse"

  /events/journeys:
    get:
      summary: Get user journeys over a period
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: "#/components/parameters/ApiKeyHeader"
        - name: period
          in: query
          required: false
          schema:
            type: string
        - name: limit
          in: query
          required: false
          schema:
            type: integer
        - name: device
          in: query
          required: false
          schema:
            type: string
        - name: country
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Array of journeys
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JourneyResponse"

  /events/users/{userId}/journey:
    get:
      summary: Get one user's journey data
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: "#/components/parameters/ApiKeyHeader"
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User's journey
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserJourneyResponse"

  /events/retention:
    get:
      summary: Get retention analytics for a cohort event
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: "#/components/parameters/ApiKeyHeader"
        - name: cohort
          in: query
          required: true
          schema:
            type: string
          description: Cohort starting event (e.g. signup, login, etc)
        - name: period
          in: query
          required: false
          schema:
            type: string
            example: "7"
          description: Days to include
        - name: targetEvent
          in: query
          required: false
          schema:
            type: string
        - name: device
          in: query
          required: false
          schema:
            type: string
        - name: country
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Retention data by cohort
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RetentionResponse"
security:
  - ApiKeyAuth: []
